### ISSUE TITLE
XML format

### ISSUE THREAD

**Issue by gree-gorey** [nevmenandr/thai-language#1]
В [образце xml](https://github.com/nevmenandr/thai-language/blob/master/example_corpus.xml), из которого делаются prs файлы для армянского движка, текст внутри тега `<w>` сейчас неудобно расположен для парсинга xml. Сейчас это выглядит так:

``` xml
<w>
  <ana lex="тере" morph="Ø" gr="ADJ,nom,sg" trans="живой" />
  тере
</w>
```

То есть это парсится, но выглядит некрасиво. Если для нас непринципиально именно такое устройство xml, можно было бы его подправить и заключить текст в какой-нибудь тег, типа того:

``` xml
<w>
  <ana lex="тере" morph="Ø" gr="ADJ,nom,sg" trans="живой" />
  <content>тере</content>
</w>
```

**Comment by nevmenandr** [comment]
Для нас это принципиально. Используйте в lxml атрибут tail и всё будет доставаться как надо.

**Comment by gree-gorey** [comment]
я понял, спасибо
