### ISSUE TITLE
ошибка парсинга в pythai

### ISSUE THREAD

**Issue by gree-gorey** [nevmenandr/thai-language#4]
в общем пока я считал токены, выявилась такая неприятность, а именно **pythai** вылетает, когда ему на вход поступают символы вроде таких `¯°.¸♥♥¯°ศรรกราหน้าทะเล้น°¯♥♥¸.°´¯`, несмотря на то, что они юникодовские.
При этом проблема возникает при вызове функции из библиотеки **libthai**. Она загружается из файла **libthai.so**, поэтому изменить там внутри что-то руками и написать какое-то исключение не получается((
Я так понимаю, что он не ругается на буквы, цифры и стандартные знаки препинания, а вот остальные знаки как-то не любит.
Сейчас я просто пропускал файлы с текстом, вызывающим такую ошибку, из 516 550 файлов она оказалась в 5 809.

а ошибка выглядит так:

```
File "/usr/local/lib/python2.7/dist-packages/pythai/pythai.py", line 22, in _split_thai_phrase
    return libthai.th_brk(phrase)
  File "/usr/lib/python2.7/encodings/cp874.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2665' in position 20: character maps to <undefined>
```

то есть это скорее конечно не моя даже проблема, а того кто будет токенизировать все файлы. Но вот как-то надо подумать как ее решить.

**Comment by nevmenandr** [comment]
Кажется, несложно решить: надо просто подсовывать **pythai** не всё подряд, а только куски текста с тайскими символами. Определять их можно регулярными выражениями или по числовому диапазону **ord**(): надо посмотреть, что из этого быстрее работает.

**Comment by gree-gorey** [comment]
решили, проверяя на тайскость символы (`3585 <= ord(char) <= 3675`) и отделяя строки из таких символов пробелами от остального текста
