### ISSUE TITLE
не работает поиск

### ISSUE THREAD

**Issue by gree-gorey** [nevmenandr/thai-language#7]
индексация завершилась удачей, проиндексировал 43 745 384 токенов.
А вот поиск теперь не работает. Задумывается надолго и всё :(

**Comment by nevmenandr** [comment]
Возможно, не смог проглотить 43 млн. Давайте запустим на 20.

**Comment by gree-gorey** [comment]
Запустил на 21 млн. -- та же история(
Попробовал на 1 млн. -- все работает.
Видимо, придется методом проб что ли искать лимит?

**Comment by nevmenandr** [comment]
Это если дело в лимите. Может быть, есть что-то в самих текстах, что ломает индекс. Давайте попробуем удалять из текстов всё, кроме таицы, латиницы, знаков препинания и цифр? То есть всё то, на чём ломался токенизатор.

**Comment by gree-gorey** [comment]
чет все равно не хочет. 20 млн. и символы только хорошие.

**Comment by nevmenandr** [comment]
Надо же, а у меня днём искал по словоформам. Может, это по миллиону было.

**Comment by nevmenandr** [comment]
Я обратился к Оракулу. Оракул думал семь дней и семь ночей, и на восьмую ночь ответил:

> Дело, видимо, не в миллионах, а в том, что в текстах всё-таки попадается что-то невалидное, и в миллионе оно не встретилось, я думаю. А слов в предложении у вас там везде нормальное количество? Не могло оказаться такого, что где-то деление на предложения не сработало? Я не знаю, как в тайском это устроено, но вот в армянском в конце предложения стоит "армянская точка", которая выглядит как двоеточие, и её часто путают с нашим двоеточием -- если в файлах разнобой, сплиттер может посчитать некоторые тексты состоящими из одного предожения, а это может повесить поиск.
> 
> Если длиной предложений точно всё везде нормально, то сделай вот что. Верни миллионы, чтобы ничего не работало. А дальше в папке client нужно взять один из файлов (не помню какой, кажется, client.php) и найти место, где применяется xsl-преобразование. В том месте, где оно применяется, нужно написать echo $XML (или как называется там переменная с XML'ем) и сразу exit. И после этого смотреть, появится ли что-то в коде фрейма с результатами. Если появится xml, то нужно его скопировать, в текстовом редакторе заменить &lt; и т. п. на скобки, а потом проверить в каком-нибудь онлайн-валидаторе.

**Comment by gree-gorey** [comment]
Слов и предложений везде нормальное количество. Я даже оставлял только тексты, в которых больше одного предложения и только предложения в которых больше одного слова. Это не помогло.

А вот место в php где все это дело зависает:
в файле `client.php` есть функция `getOneResult` в которой следующая строка:

```
# Вытаскиваем XML предложения из БД
$sentence = $this->db->getValue(...);
```

и вот короче эта функция `getValue` из файла `db.php` должна делать запрос к БД и возвращать xml одного предложения

когда корпус маленький, она работает как нужно и если вставить в месте ретёрна `echo` то возвращает она такое:

```
<c></c>
<w>พระ<graphs><graph></graph></graphs><indexingword>พระ</indexingword><n>7</n><gloss><lem>พระ</lem><trans>priest</trans><lex></lex><gram></gram><flex></flex></gloss><gloss><lem>พระ</lem><trans>pastor</trans><lex></lex><gram></gram><flex></flex></gloss><gloss><lem>พระ</lem><trans>leading actor</trans><lex>noun</lex><gram></gram><flex></flex></gloss><gloss><lem>พระ</lem><trans>monk</trans><lex>noun</lex><gram></gram><flex></flex></gloss><gloss><lem>พระ</lem><trans>Buddha image</trans><lex>noun</lex><gram></gram><flex></flex></gloss><gloss><lem>พระ</lem><trans>holy Joe</trans><lex></lex><gram></gram><flex></flex></gloss><gloss><lem>พระ</lem><trans>presbyter</trans><lex></lex><gram></gram><flex></flex></gloss></w>
<w>นคร<graphs><graph></graph></graphs><indexingword>นคร</indexingword><n>1</n><gloss><lem>นคร</lem><trans>city</trans><lex>noun</lex><gram></gram><flex></flex></gloss></w>
<w>ศรี<graphs><graph></graph></graphs><indexingword>ศรี</indexingword><n>1</n><gloss><lem>ศรี</lem><trans>honour</trans><lex>noun</lex><gram></gram><flex></flex></gloss></w>
```

то есть нормальный xml со списком слов предложения.

А когда проиндексирован большой корпус то она возвращает... число о_О. 42. Разные числа возвращает один раз, а дальше виснет (хотя должна для каждого предложения запускаться).
Причем номера найденных предложений (`$sent_no`) и ид документов (`$doc_id`) передаются, это все в порядке.

Как-то так.
Дальше кажется снова нужен Оракул.

**Comment by nevmenandr** [comment]
> Дело вот в чём. В индексаторе есть вот такие строки, которые должны выполняться в самом конце:
>        self.mysql.query("ALTER TABLE lemmas add key lemma(lemma);");
>        self.mysql.query("ALTER TABLE lemmas add key trans(trans);");
>        self.mysql.query("ALTER TABLE wordforms add key wordform(wordform);");
>        self.mysql.query("ALTER TABLE gramcodes add key gramcode(gramcode);");
>        self.mysql.query("ALTER TABLE sentences add key wordaddress(doc_id, sent_no);");
>        self.mysql.query("ALTER TABLE complex add key wordform(wordform, gramcode);");
>        self.mysql.query("ALTER TABLE complex add key lemma(lemma, gramcode);");
>        self.mysql.query("ALTER TABLE complex add key trans(trans, gramcode);");

> Они создают индексы в таблицах. Иногда -- и я не знаю, когда именно и почему, но такое бывает редко -- эти индексы не создаются. В этом случае индексатор печатает на экран строки с SQL-командами, которые не удалось выполнить, но не падает. А если нет индекса (в первую очередь в таблице sentences) -- результат может искаться неделями. Это лечится выполнением всех этих команд вручную в phpmyadmin или просто через консоль. Когда такое происходит у меня, я это сразу вижу, потому что индексатор пишет эти строчки, а тут я сразу не сообразил, потому что не запускал индексатор сам. Короче, имейте в виду. Сейчас вроде всё работает. (Ну, то есть, в каких-то результатах ничего не видно, но это скорее уже что-то не то произошло при разметке.)
